modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SnappyDragon18/Habitat/issues"

[[mods]]
  modId="habitat"
  version="0.3"
  displayName="Habitat"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/habitat"
  logoFile="logo.png"
  authors="SchnappDragon, Edmord17"
  description='''Mod that aims to enhance the Overworld by adding content to old biomes and adding new biomes.'''

  [[dependencies.habitat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"